apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-management 
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: namaspace-management
  source:
    path: NameSpaceManagement
    repoURL: https://github.com/rv2023/K8OpsManagement.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
      #  summary: {}
      #sourceType: Kustomize
