apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: resource-management
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster: dev
            url: https://kubernetes.default.svc
            values:
              project: dev
          - cluster: prod
            url: https://kubernetes.default.svc
            values:
              project: prod
      - git:
          repoURL: https://github.com/rv2023/K8OpsManagement.git
          revision: HEAD
          directories:
          - path: ClusterResource/NameSpace/*
          #value:
          #  base_dir: ClusterResource/NameSpaces/
  template:
    metadata:
      name: '{{ path[4] }}-{{ cluster }}'
    spec:
      project: '{{ cluster }}'
      source:
        repoURL: https://github.com/rv2023/K8OpsManagement.git
        targetRevision: HEAD
        path: '{{ .path.path }}'
        helm:
           releaseName: '{{cluster}}-{{.path.basename}}-resource'
           #valueFiles:
           #- '$base_dir/{{.path.basename}}/Resources/values-{{cluster}}.yaml'
      destination:
        server: '{{ url }}'
        namespace: '{{ .path.basename }}'