apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sbx-res-mgmt
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/rv2023/K8OpsManagement.git
          revision: HEAD
          directories:
          - path: ClusterResources/NameSpaces/*
      - list:
          elements:
          - cluster: dev
            url: https://kubernetes.default.svc
          - cluster: prod
            url: https://kubernetes.default.svc
  # generators:
  # - git:
  #     repoURL: https://github.com/rv2023/K8OpsManagement.git
  #     revision: HEAD
  #     directories:
  #     - path: ClusterResources/NameSpaces/*
  #     values:
  #       base_dir: ../../
  #goTemplate: true
  #goTemplateOptions:
  #- missingkey=error
  template:
    metadata:
      name: resource-management-{{ cluster }}-{{ path[2] }}-application
    spec:
      project: "default"
      source:
        path:  GlobalResources/ResourceQuota
        repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
        helm:
          releaseName: 'resource-{{ cluster }}-{{ path[2] }}-helm-release'
          valueFiles:
          - '../../ClusterResources/NameSpaces/{{path[2]}}/Resources/values-{{ cluster }}.yaml'
      # destination:
      #   server: 'https://kubernetes.default.svc'
      #   namespace: '{{ path[2] }}'
      destination:
        server: '{{ .url }}'
        namespace: '{{ path[2] }}-{{} cluster }}'