apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server-application-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - cluster: sandbox
          url: https://kubernetes.default.svc
          chartVersion: 4.1.3
        - cluster: dev
          url: https://kubernetes.default.svc
          chartVersion: 4.1.5
        - cluster: prod
          url: https://kubernetes.default.svc
          chartVersion: 5.0.0
  template:
    metadata:
      name: 'metrics-server-{{ cluster }}-application'
    spec:
      project: '{{ cluster }}'
      sources:
        - path:  metrics-server/metrics-server
          repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
          targetRevision: '{{chartVersion}}'
          helm:
            releaseName: 'metrics-server-{{ cluster }}-helm-release'
            valueFiles:
             - '../../Clusters/ClusterConfigs/ClusterAddons/metrics-sever/{{ cluster }}/values.yaml'
      destination:
        name:
        server: '{{url}}'
        namespace: 'metrics-server-{{ cluster }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true