apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-management-matrix
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/rv2023/K8OpsManagement.git
          revision: HEAD
          directories:
          - path: Clusters/NameSpaces/*
      - list:
          elements:
          - cluster: dev
            url: https://kubernetes.default.svc
          - cluster: sandbox
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: user-management-{{ cluster }}-{{ path[2] }}-application
    spec:
      project: '{{ cluster }}'
      source:
        path:  HelmCharts/UserManagement
        repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
        helm:
          releaseName: 'users-{{ cluster }}-{{ path[2] }}-helm-release'
          valueFiles:
          - 'values.yaml'
          - '../../Clusters/NameSpaces/{{path[2]}}/Users/values-{{ cluster }}.yaml'
          #- '../../Clusters/ClusterConfigs/UserManagement/{{ cluster }}/values.yaml'
      destination:
        server: '{{ url }}'
        namespace: '{{ path[2] }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true