apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server-application-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - cluster: sandbox
          url: https://kubernetes.default.svc
          chartVersion: 4.1.3
        - cluster: dev
          url: https://kubernetes.default.svc
          chartVersion: 4.1.5
        - cluster: prod
          url: https://kubernetes.default.svc
          chartVersion: 5.0.0
  template:
    metadata:
      name: 'metrics-server-{{ cluster }}-application'
    spec:
      project: '{{ cluster }}'
      sources:
      sources:
        - path:  metrics-server/metrics-server
          repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
          targetRevision: '{{chartVersion}}'
          helm:
            releaseName: '{{cluster}}-metrics-server'
            valueFiles:
            - '$values/Clusters/ClusterConfigs/ClusterAddons/metrics-sever/{{ cluster }}/values.yaml'
        - repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
          targetRevision: HEAD
          ref: values
#- '$values/Clusters/ClusterConfigs/ClusterAddons/metrics-sever/{{ cluster }}/values.yaml'
      destination:
        server: '{{url}}'
        namespace: 'metrics-server-{{ cluster }}'
#      syncPolicy:
#        automated:
#          prune: true
#          selfHeal: true
#        syncOptions:
#          - CreateNamespace=true
#          - ApplyOutOfSyncOnly=true
