apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: resource-management
  namespace: argocd
spec:
  generators:
  - git:
       repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
       revision: HEAD
       files:
       - path: NameSpaces/*/Resources/values.yaml
  template:
    metadata:
      name: 'resource-{{ path[1] }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: resource-management
      sources:
        - path: HelmCharts/ResourceQuota
          repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
          targetRevision: HEAD
          helm:
            releaseName: 'resource-{{ path[1] }}'
            valueFiles:
            - $values/NameSpaces/{{path[1]}}/Resources/values.yaml
        - repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
          targetRevision: HEAD
          ref: values
      destination:
        # Default base cluster
        name:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ path[1] }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
