apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-git
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/argoproj/argo-cd.git
          revision: HEAD
          directories:
          - path: applicationset/examples/matrix/cluster-addons/*
      - list:
          elements:
          - cluster: dev
            url: https://1.2.3.4
            values:
              project: dev
          - cluster: prod
            url: https://2.4.6.8
            values:
              project: prod
  template:
    metadata:
      name: '{{ path[4] }}-{{ cluster }}'
    spec:
      project: '{{ cluster }}'
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        server: '{{ .url }}'
        namespace: '{{ .path.basename }}'

        