apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: resource-management
  namespace: argocd
spec:
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
              revision: HEAD
              directories:
              - path: ClusterResource/NameSpace/*
          # cluster generator, 'child' #2
          - list:
              elements:
                - cluster: sandbox
                  url: https://kubernetes.default.svc
                - cluster: nonprod
                  url: https://kubernetes.default.svc
                - cluster: prod
                  url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-resource-management'        
      argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: '{{cluster}}-resource-management'
      sources:
        - path: GlobalResource/ResourceQuota
          repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
          targetRevision: HEAD
          helm:
            releaseName: 'resource-{{cluster}}-{{ path[1] }}'
            valueFiles:
            - '$values/ClusterResource/NameSpaces/{{path[1]}}/Resources/values-{{cluster}}.yaml'
        - repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
          targetRevision: HEAD
          ref: values
      destination:
        name:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true