apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/rv2023/K8OpsManagement.git
      revision: HEAD
      directories:
      - path: ClusterResource/NameSpace/*
  template:
    metadata:
      name: resource-management'
    spec:
      project: "default"
      sources:
        - path:  GlobalResources/ResourceQuota
          repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
          helm:
            releaseName: '{{ path[2] }}-resource'
            valueFiles:
            - '$valuesClusterResource/NameSpace/{{path[2]}}/values-sandbox.yaml'
        - repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
          targetRevision: HEAD
          ref: values
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ path[1] }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true