{{- range .Values.pvclaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  storageClassName: {{ .storageClassName }}
  accessModes:
    {{ .accessModes | toYaml }}
  resources:
    requests:
      storage: {{ .storage }}
{{- end }} 