apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globleresource-management 
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
    path: ClusterResources/GlobalResource
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true