apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-management
  namespace: argocd
spec:
  generators:
  - git:
       repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
       revision: HEAD
       files:
#       - path: UserManagement/namespaces/namespace-c/values.yaml
       - path: UserManagement/namespaces/*/values.yaml
  template:
    metadata:
      name: 'users-{{ path[2] }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: user-management
      #project: default
      sources:
        - path: UserManagement/configurations
          repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
          targetRevision: HEAD
          helm:
            releaseName: 'users-{{ path[2] }}'
            valueFiles:
            #- $values/UserManagement/configurations/values.yaml
            - $values/UserManagement/namespaces/{{path[2]}}/values.yaml
        - repoURL: 'https://github.com/rv2023/K8OpsManagement.git'
          targetRevision: HEAD
          ref: values
      destination:
        # Default base cluster
        name:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ path[2] }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
