apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - appName: namespace-a
          namespace: namespace-a
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: bootstrap
      source:
        repoURL: "https://github.com/rv2023/K8OpsManagement.git"
        targetRevision: HEAD
        path: "UserManagement/configure-user"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - "UserManagement/namespaces/{{appName}}/values.yaml"
      destination:
        # Default base cluster
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
